name       : jbig2dec
version    : 0.18
release    : 1
source     :
    - https://github.com/ArtifexSoftware/jbig2dec/archive/0.18.tar.gz : 3be6eb8105f6dcc8a7d29d6f2b4dc9205c164a412ad940294cedf0d7cc530487
license    : AGPL-3.0-or-later
homepage   : https://jbig2dec.com/
component  : multimedia.library
summary    : A decoder implementation of the JBIG2 image compression format
description: |
    jbig2dec is a decoder library and example utility implementing the JBIG2 bi-level image compression spec.
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
