name       : jbig2dec
version    : "0.19"
release    : 2
source     :
    - https://github.com/ArtifexSoftware/jbig2dec/archive/0.19.tar.gz : e81b787ad0b147a437a52d9ce7de1a8f429655e8aa030383b6b2dd8919373717
homepage   : https://jbig2dec.com/
license    : AGPL-3.0-or-later
component  : multimedia.library
summary    : A decoder implementation of the JBIG2 image compression format
description: |
    jbig2dec is a decoder library and example utility implementing the JBIG2 bi-level image compression spec.
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
